
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: server
    marker: practice
  name: server
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'true'
      labels:
        app: server
    spec:
      containers:
        - image: >-
            registry.delta.sbrf.ru/base/hello-openshift:v3.9.0
          name: server
          resources:
            limits:
              cpu: 0.5
              memory: 512Mi
            requests:
              cpu: 0.5
              memory: 512Mi
---
kind: Service
apiVersion: v1
metadata:
  name: server
  labels:
    app: server
    marker: practice
spec:
  ports:
    # Обратите внимание на название порта
    - name: tcp-8080
      port: 8080
    - name: tcp-8888
      port: 8888
  selector:
    app: server